version: '2'

services:
    build:
        restart: always
        build: .
        image: cr8ivecodesmith/py3kit:latest
        container_name: py3kit
        user: py3kit
    notebook:
        extends:
            service: build
        ports:
            - "8888:8888"
        command: ipython notebook
    ipython:
        extends:
            service: build
        command: ipython
