version: '2'

services:
    build:
        restart: always
        build: .
        image: cr8ivecodesmith/pykit:2.7
        container_name: py2kit
        user: pykit
    notebook:
        extends:
            service: build
        ports:
            - "8888:8888"
        command: ipython notebook
    ipython:
        extends:
            service: build
        command: ipython
