# Usage:
# Copy this compose file to your project's directory.
#
# Always run this with the context of the current user:
# docker-compose run --rm -u "$(id -u):$(id -g)" --service-ports kit <commands>
#
version: '2'

services:
    build:
        restart: always
        build: .
        image: cr8ivecodesmith/pykit:2.7
        container_name: py3kit
        volumes:
            - .:/usr/src/project
        working_dir: "/usr/src/project"
    kit:
        extends:
            service: build
        ports:
            - "8888:8888"
            - "8000:8000"
            - "5000:5000"
