FROM ubuntu:16.04
ENV DEBIAN_FRONTEND noninteractive
MAINTAINER matt lebrun <matt@lebrun.org>

# Update system and install required software
RUN apt-get update --fix-missing && apt-get install -y \
    wget \
    curl \
    build-essential \
    autoconf \
    libtool \
    software-properties-common \
    libpcre3 \
    libpcre3-dev \
    libssl-dev \
    zlib1g \
    zlib1g-dev \
    libgeoip1 \
    libgeoip-dev

# Install Maxmind libs
RUN add-apt-repository ppa:maxmind/ppa \
    && apt-get update && apt-get install -y \
        libmaxminddb0 \
        libmaxminddb-dev \
        mmdb-bin

# Download MaxMind GeoLite databases
RUN mkdir -p /usr/share/GeoIP/ &&\
    wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz &&\
    gunzip GeoLiteCity.dat.gz &&\
    mv -f GeoLiteCity.dat /usr/share/GeoIP/ &&\
    wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz &&\
    gunzip GeoIP.dat.gz &&\
    mv -f GeoIP.dat /usr/share/GeoIP/

# Download Nginx
ENV nginx_version 1.13.1
RUN curl http://nginx.org/download/nginx-$nginx_version.tar.gz | tar xz

WORKDIR /nginx-$nginx_version

# Compile Nginx
RUN ./configure \
    --prefix=/etc/nginx \
    --sbin-path=/usr/sbin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/var/run/nginx.pid \
    --lock-path=/var/run/nginx.lock \
    --http-client-body-temp-path=/var/cache/nginx/client_temp \
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
    --user=nginx \
    --group=nginx \
    --with-http_ssl_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_stub_status_module \
    --with-http_auth_request_module \
    --with-http_geoip_module \
    --with-threads \
    --with-stream \
    --with-stream_ssl_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-file-aio \
    --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' \
    --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' \
    --with-ipv6 \
    && make && make install \
    && mkdir -p /var/cache/nginx

# Cleanup
RUN apt-get autoclean \
    && apt-get autoremove \
    && apt-get purge \
    && rm -rfv /*.gz \
    && rm -rfv /tmp/* \
    && rm -rfv /var/tmp/* \
    && rm -rfv /nginx-$nginx_version

WORKDIR /

# forward request logs to Docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
